import Head from "next/head";
import { Inter } from "next/font/google";
import Section1 from "@/src/components/About/Section1";
import Section2 from "@/src/components/About/Section2";
import Section3 from "@/src/components/About/Section3";
import Section4 from "@/src/components/About/Section4";
import Section5 from "@/src/components/About/Section5";
import Section6 from "@/src/components/About/Section6";
import Section7 from "@/src/components/About/Section7";
import Section8 from "@/src/components/About/Section8";
import Section9 from "@/src/components/About/Section9";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section1 />
      <Section2 />
      <Section3 />
      <Section4 />
      <Section5 />
      <Section6 />
      <Section7 />
      <Section8 />
      <Section9 />
    </>
  );
}
